baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Code Playground"
theme = "PaperMod"

[params]
  author = "Tia Kavousi"
  description = "A multi-language code playground"
  ShowReadingTime = false
  ShowShareButtons = false

