FROM docker:dind

# Install Go
RUN apk add --no-cache go

# Install other dependencies
RUN apk add --no-cache \
    python3 \
    nodejs \
    openjdk11 \
    gcc \
    g++ \
    bash \
    docker-cli


WORKDIR /app

COPY ./Backend/go.mod ./Backend/go.sum ./
RUN go mod download

COPY ./Backend/ .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o code-playground ./cmd/main.go

EXPOSE 8080

CMD ["dockerd-entrypoint.sh", "./code-playground"]