version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 512m
    cpu_shares: 512
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_WS_URL=backend:8080

  # Service for code execution
  code_executor:
    image: tayebe/repl
    command: echo "Code execution container ready"
    deploy:
      replicas: 0 # This ensures the container doesn't actually run, we just want the image
    pull_policy: always # This ensures the image is always pulled

networks:
  default:
    driver: bridge
