version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    mem_limit: 512m
    cpu_shares: 512
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /app/temp:rw,exec,nosuid,nodev # writable temporary directory that the application can use
    environment:
      - GIN_MODE=release
      - TEMP_DIR=/app/temp

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_WS_URL=backend:8080

networks:
  default:
    driver: bridge
