FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    openjdk-17-jdk \
    nodejs

ENV PATH="/usr/bin:$PATH" 

CMD [ "bash" ]