FROM node:16-alpine

WORKDIR /app

COPY ./Frontend/package*.json ./

RUN npm install

COPY ./Frontend/ .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]