name: Quality
on: [push, pull_request]

jobs:
  dind-job:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
        driver-opts: |
          network=host

    - name: Use Docker
      env:
        DOCKER_HOST: tcp://localhost:2375
      run: |
        docker version
        docker pull phantasm/busybox
        # Add your Docker commands here

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Run tests
      env:
        DOCKER_HOST: tcp://localhost:2375
      run: |
        cd backend && go test -race -covermode atomic -coverprofile=covprofile -timeout 30s ./pkg/executor/...